name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t spring-app \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:latest \
            ./springboot/app

      - name: Build frontend image
        run: |
          docker build \
            -t angular-app \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest \
            ./angular-app

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest

      - name: Test application with Docker Compose
        run: |
          docker compose up -d
          docker compose ps
          sleep 25
          curl -f http://localhost:8081
          curl -f http://localhost:4200
